version: '3.4'
services:
  frequi:
    build:
      context: ..
      target: dev
      dockerfile: .devcontainer/Dockerfile
    image: freqtradeorg/frequi:dev
    user: dev
    volumes:
      - ../:/home/dev/frequi
      - frequi-node-modules:/home/dev/frequi/node_modules

      - "${HOME}/.ssh:/home/dev/.ssh:ro"
      - "${HOME}/.gitconfig:/home/dev/.gitconfig:ro"
      - frequi-bashhistory:/home/dev/commandhistory
      - frequi-vscode-server:/home/dev/.vscode-server
      - frequi-server-insiders:/home/dev/.vscode-server-insiders
    command: /bin/bash -c "while sleep 1000; do :; done"
    # networks:
    #   - frequi
    ports:
      - 8080:8080

# networks:
#   frequi:

volumes:
  frequi-node-modules:
  frequi-bashhistory:
  frequi-vscode-server:
  frequi-server-insiders:
