version: '3.4'
services:
  web:
    build:
      context: ..
      target: dev
      dockerfile: .devcontainer/Dockerfile
    image: freqtradeorg/frequi:dev
    user: dev
    volumes:
      - ../:/home/dev/frequi
      - frequi-node-modules:/home/dev/frequi/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    # networks:
    #   - frequi
    ports:
      - 8080:8080

# networks:
#   frequi:

volumes:
  frequi-node-modules:
